/**
 * The managed Yazi profile is a reproducible cache artifact. These contracts
 * pin its bytes, its compatibility with Yazi 26.8.15, and the rule that Clio
 * never reads or writes the operator's own Yazi configuration.
 */

import { deepStrictEqual, match, ok, strictEqual } from "node:assert/strict";
import { chmodSync, mkdirSync, mkdtempSync, readFileSync, rmSync, statSync, writeFileSync } from "node:fs";
import { homedir, tmpdir } from "node:os";
import { join } from "node:path";
import { after, before, describe, it } from "node:test";
import { tokenHex } from "../../src/core/theme-token-hex.js";
import { parseTomlDocument, tomlTableAt } from "../../src/core/toml.js";
import {
	describeYaziProfile,
	ensureYaziProfile,
	inspectYaziProfile,
	renderYaziKeymap,
	userYaziConfigDir,
} from "../../src/domains/mux/yazi/profile.js";
import { renderYaziTheme } from "../../src/domains/mux/yazi/theme.js";
import { findPinnedTool } from "../../src/domains/toolchain/registry.js";
import { type ClioToken, createClioTheme } from "../../src/interactive/theme/tokens.js";

const ASSETS = join(process.cwd(), "src", "domains", "mux", "yazi", "assets");
const FIXTURES = join(process.cwd(), "tests", "fixtures", "yazi");
const YA = "/opt/clio tools/ya";
const YAZI_ENTRY = findPinnedTool("yazi");
const VENDORED_YAZI_CANDIDATE = join(
	process.env.XDG_DATA_HOME ?? join(homedir(), ".local", "share"),
	"clio-coder",
	"tools",
	"yazi",
	YAZI_ENTRY?.version ?? "unknown",
	process.platform === "win32" ? "yazi.exe" : "yazi",
);
const VENDORED_YAZI = statSync(VENDORED_YAZI_CANDIDATE, { throwIfNoEntry: false })?.isFile()
	? VENDORED_YAZI_CANDIDATE
	: null;
const CLIO_TOKENS: readonly ClioToken[] = [
	"accent",
	"accentDeep",
	"action",
	"success",
	"warning",
	"error",
	"info",
	"reason",
	"dim",
	"muted",
	"title",
	"frame",
	"frameStrong",
];

const THEME_GOLDEN = `# Generated by Clio Coder. Changes are replaced when the managed profile regenerates.

[mgr]
cwd = { fg = "#46e5d0" }
find_keyword = { fg = "#ffb454" }
marker_selected = { fg = "#57e389", bg = "#57e389" }
marker_copied = { fg = "#46e5d0", bg = "#46e5d0" }
marker_cut = { fg = "#ff5c66", bg = "#ff5c66" }
border_style = { fg = "#2f5d5a" }

[mode]
normal_main = { bg = "#46e5d0" }
normal_alt = { fg = "#46e5d0" }
select_main = { bg = "#ff7e29" }
select_alt = { fg = "#ff7e29" }
unset_main = { bg = "#ff5c66" }
unset_alt = { fg = "#ff5c66" }

[tabs]
active = { bg = "#46e5d0" }
inactive = { fg = "#46e5d0" }

[status]
perm_sep = { fg = "#6a7a85" }
`;

const KEYMAP_GOLDEN = `# Generated by Clio Coder. Changes are replaced when the managed profile regenerates.

[[mgr.prepend_keymap]]
on   = "<C-y>"
run  = "shell -- '/opt/clio tools/ya' pub-to \\"$YAZI_ID\\" clio-pick --list \\"$CLIO_YAZI_PICK_TOKEN\\" %s"
desc = "Send the selection to Clio"
`;

function record(value: unknown): value is Record<string, unknown> {
	return typeof value === "object" && value !== null && !Array.isArray(value);
}

function assertKeysExist(generated: unknown, preset: unknown, path: string): void {
	ok(record(generated), `${path} is a generated table`);
	ok(record(preset), `${path} exists in the pinned preset`);
	for (const [key, value] of Object.entries(generated)) {
		ok(Object.hasOwn(preset, key), `${path}.${key} exists in Yazi 26.8.15`);
		if (record(value)) assertKeysExist(value, preset[key], `${path}.${key}`);
	}
}

describe("contracts/yazi managed profile", () => {
	let scratch: string;
	let profileDir: string;
	let fakeYazi: string;

	before(() => {
		scratch = mkdtempSync(join(tmpdir(), "clio-yazi-profile-"));
		profileDir = join(scratch, "cache", "yazi", "profile");
		fakeYazi = join(scratch, "schema-checking-yazi.mjs");
		writeFileSync(
			fakeYazi,
			`#!/usr/bin/env node
import { readFileSync } from "node:fs";
import { join } from "node:path";
const configHome = process.env.YAZI_CONFIG_HOME;
const config = readFileSync(join(configHome, "yazi.toml"), "utf8");
const fetchers = config.split("[[plugin.prepend_fetchers]]").slice(1);
if (fetchers.length === 0 || fetchers.some((entry) => !/^\\s*group\\s*=/mu.test(entry))) {
	process.stderr.write("Failed to parse config\\nmissing field group\\nPress <Enter> to continue with preset settings...\\n");
	process.exit(1);
}
process.stdout.write("Yazi debug profile loaded\\n");
`,
		);
		chmodSync(fakeYazi, 0o755);
	});

	after(() => {
		rmSync(scratch, { recursive: true, force: true });
	});

	it("renders byte-pinned theme, seed config, and keymap files", () => {
		strictEqual(renderYaziTheme(), THEME_GOLDEN);
		strictEqual(renderYaziKeymap(YA), KEYMAP_GOLDEN);
		const profile = ensureYaziProfile({
			yaPath: YA,
			yaziPath: fakeYazi,
			profileDir,
			assetDir: ASSETS,
			yaziVersion: "26.8.15",
			clioVersion: "0.4.0",
		});
		ok(profile);
		strictEqual(readFileSync(join(profileDir, "theme.toml"), "utf8"), THEME_GOLDEN);
		strictEqual(readFileSync(join(profileDir, "keymap.toml"), "utf8"), KEYMAP_GOLDEN);
		strictEqual(readFileSync(join(profileDir, "yazi.toml"), "utf8"), readFileSync(join(ASSETS, "yazi.toml"), "utf8"));
		strictEqual(readFileSync(join(profileDir, "init.lua"), "utf8"), readFileSync(join(ASSETS, "init.lua"), "utf8"));
		strictEqual(
			readFileSync(join(profileDir, "plugins", "git.yazi", "LICENSE"), "utf8"),
			readFileSync(join(ASSETS, "plugins", "git.yazi", "LICENSE"), "utf8"),
		);
		strictEqual(statSync(join(profileDir, "package.toml"), { throwIfNoEntry: false }), undefined);
	});

	it("supplies the fetcher group required by Yazi 26.8.15", () => {
		const generated = parseTomlDocument(readFileSync(join(ASSETS, "yazi.toml"), "utf8"));
		ok(generated);
		const plugin = tomlTableAt(generated, ["plugin"]);
		ok(plugin);
		const fetchers = plugin.prepend_fetchers;
		ok(Array.isArray(fetchers));
		deepStrictEqual(
			fetchers.map((entry) => (record(entry) ? entry.group : null)),
			["git", "git"],
		);
	});

	it("loads the generated profile with the installed vendored Yazi at the pin", {
		skip: VENDORED_YAZI === null ? "the vendored Yazi pin is not installed" : false,
	}, () => {
		ok(VENDORED_YAZI);
		const actualProfileDir = join(scratch, "actual-yazi-profile");
		ok(
			ensureYaziProfile({
				yaPath: YA,
				yaziPath: VENDORED_YAZI,
				profileDir: actualProfileDir,
				assetDir: ASSETS,
				yaziVersion: "26.8.15",
				clioVersion: "0.4.0",
			}),
		);
	});

	it("keeps the generated hex projection aligned with the interactive palette", () => {
		const theme = createClioTheme({ truecolor: true, color: true });
		for (const token of CLIO_TOKENS) {
			const [red, green, blue] =
				tokenHex(token)
					.slice(1)
					.match(/.{2}/gu)
					?.map((channel) => Number.parseInt(channel, 16)) ?? [];
			strictEqual(theme.fgSequence(token), `\u001b[38;2;${red};${green};${blue}m`, token);
		}
	});

	it("uses only theme tables and keys legal at the pin", () => {
		const generated = parseTomlDocument(renderYaziTheme());
		const preset = parseTomlDocument(readFileSync(join(FIXTURES, "theme-dark-v26.8.15.toml"), "utf8"));
		ok(generated);
		ok(preset);
		assertKeysExist(generated, preset, "theme");
	});

	it("keeps the managed pick chord clear of the pinned default keymap", () => {
		const preset = parseTomlDocument(readFileSync(join(FIXTURES, "keymap-default-v26.8.15.toml"), "utf8"));
		ok(preset);
		const mgr = tomlTableAt(preset, ["mgr"]);
		ok(mgr);
		const keymap = mgr.keymap;
		ok(Array.isArray(keymap));
		const bound = keymap.some((entry) => {
			if (!record(entry)) return false;
			return entry.on === "<C-y>" || (Array.isArray(entry.on) && entry.on.includes("<C-y>"));
		});
		strictEqual(bound, false);
	});

	it("does not rewrite a current profile and regenerates when rendered theme input changes", () => {
		const options = {
			yaPath: YA,
			yaziPath: fakeYazi,
			profileDir,
			assetDir: ASSETS,
			yaziVersion: "26.8.15",
			clioVersion: "0.4.0",
		};
		ok(ensureYaziProfile(options));
		const stampPath = join(profileDir, "stamp.json");
		const first = statSync(stampPath);
		ok(ensureYaziProfile(options));
		const second = statSync(stampPath);
		strictEqual(second.ino, first.ino, "a matching stamp leaves the directory in place");

		const changedTheme = `${renderYaziTheme()}\n# simulated token change\n`;
		ok(ensureYaziProfile({ ...options, themeToml: changedTheme }));
		const third = statSync(stampPath);
		ok(third.ino !== first.ino, "a changed rendered theme replaces the profile");
		strictEqual(readFileSync(join(profileDir, "theme.toml"), "utf8"), changedTheme);
	});

	it("deletes the managed directory and refuses a generated profile whose TOML does not parse", () => {
		mkdirSync(profileDir, { recursive: true });
		writeFileSync(join(profileDir, "old"), "managed residue");
		const result = ensureYaziProfile({
			yaPath: YA,
			yaziPath: fakeYazi,
			profileDir,
			assetDir: ASSETS,
			yaziVersion: "26.8.15",
			clioVersion: "0.4.0",
			themeToml: "[mgr\nnot valid",
		});
		strictEqual(result, null);
		strictEqual(statSync(profileDir, { throwIfNoEntry: false }), undefined);
	});

	it("refuses parseable TOML that the Yazi schema rejects before promotion", () => {
		mkdirSync(profileDir, { recursive: true });
		writeFileSync(join(profileDir, "old"), "managed residue");
		const result = ensureYaziProfile({
			yaPath: YA,
			yaziPath: fakeYazi,
			profileDir,
			assetDir: ASSETS,
			yaziVersion: "26.8.15",
			clioVersion: "0.4.0",
			yaziToml: `[mgr]
show_hidden = true

[[plugin.prepend_fetchers]]
id = "git"
url = "*"
run = "git"
`,
		});
		strictEqual(result, null);
		strictEqual(statSync(profileDir, { throwIfNoEntry: false }), undefined);
	});

	it("reports Clio's cache and the user's config as separate paths without touching the latter", () => {
		const userDir = join(scratch, "operator-config", "yazi");
		const env = { XDG_CONFIG_HOME: join(scratch, "operator-config") };
		strictEqual(userYaziConfigDir(env), userDir);
		strictEqual(statSync(userDir, { throwIfNoEntry: false }), undefined);
		const inspection = inspectYaziProfile({
			yaPath: YA,
			profileDir,
			assetDir: ASSETS,
			yaziVersion: "26.8.15",
			clioVersion: "0.4.0",
		});
		match(describeYaziProfile(inspection), /user config .* is separate and untouched/u);
		deepStrictEqual(inspection.dir, profileDir);
	});
});
