import { type Static, type TSchema, Type } from "typebox";
import { AsideAnswer, AsideAskRequest, AsideCancelled, AsideDraftRequest, AsideDrafts } from "./aside.js";
import { TURN_FILE_MAX, TURN_IMAGE_MAX, TurnFile, TurnImage } from "./attachments.js";
import {
	DecisionSuperseded,
	DecisionSupersedeRequest,
	MemoryProposed,
	MemoryProposeRequest,
	SessionBoard,
} from "./board.js";
import { BranchRequest, BranchSwitched, Forked, SessionTree } from "./branches.js";
import { AgentCapabilities } from "./capabilities.js";
import { Empty, Id } from "./common.js";
import { ContextLedger } from "./context-ledger.js";
import { EventCursor } from "./events.js";
import { EvidenceDetail, EvidencePage } from "./evidence.js";
import { ExtensionReload, SessionExtensions } from "./extensions.js";
import {
	Councils,
	DispatchRun,
	DispatchRuns,
	FleetGates,
	FleetPageQuery,
	FleetReceipt,
	FleetRootDetail,
	FleetRoots,
} from "./fleet.js";
import { FleetPreview, FleetPreviewRequest, FleetRunRequest, FleetRunResult } from "./fleet-run.js";
import {
	HandoffCancelled,
	HandoffCancelRequest,
	HandoffCommitRequest,
	HandoffCommitted,
	HandoffDraft,
	HandoffPrepareRequest,
} from "./handoff.js";
import { InterviewRound, InterviewSubmission } from "./interviews.js";
import {
	LibraryAgents,
	LibraryApplyResult,
	LibraryExtensions,
	LibraryInventory,
	LibraryPlan,
	LibraryPlanParams,
	LibraryPlanReleased,
	LibraryPlanRequest,
	LibraryVerifiers,
} from "./library.js";
import { Meta } from "./meta.js";
import { Accepted, Operation } from "./operations.js";
import { PermissionDecision } from "./permissions.js";
import { UsageReport } from "./reports.js";
import { SessionConfig, SetConfigOption } from "./session-config.js";
import { PathCompletion, SessionSnapshot, SessionSummary, Workspace, WorkspacePick } from "./sessions.js";
import { ConfigGraph, SettingsReport } from "./settings.js";
import { SettingsControls, SettingWrite, SettingWritten } from "./settings-controls.js";
import { Autonomy, AutonomyLevel, SafeSettings, SafeSettingsPatch } from "./settings-safe.js";
import { SetupAnswer, SetupStart, SetupState, SetupStatus } from "./setup.js";
import {
	CommandCatalog,
	CommandRequest,
	CommandResult,
	DispatchSteerRequest,
	DispatchSteerResult,
	InterruptRequest,
	InterruptResult,
	QueueCleared,
	QueueSnapshot,
	SteerRequest,
	SteerResult,
} from "./steering.js";
import { Interop, InteropDecided, InteropDecision, InteropQuery, SystemReport } from "./system.js";
import { SessionTargets, TargetProbe } from "./targets.js";
import { CliTargets, Routing } from "./targets-cli.js";
import { Install, Tools } from "./toolchain.js";
import {
	RowCursor,
	TraceEventsPage,
	TraceEventsQuery,
	TraceGate,
	TraceParams,
	TracePhase,
	TraceProcess,
	TraceReceipt,
	TraceRun,
	TraceRunsPage,
	TraceRunsQuery,
	TraceStatus,
} from "./traces.js";
import { SessionUsage } from "./usage.js";

export interface Route<
	P extends TSchema = TSchema,
	Q extends TSchema = TSchema,
	B extends TSchema = TSchema,
	R extends TSchema = TSchema,
> {
	method: "GET" | "POST" | "PATCH" | "DELETE";
	path: string;
	params: P;
	query: Q;
	body: B;
	response: R;
	status: 200 | 202;
	summary: string;
	stream?: true;
}
export function defineRoute<P extends TSchema, Q extends TSchema, B extends TSchema, R extends TSchema>(
	route: Route<P, Q, B, R>,
): Route<P, Q, B, R> {
	return route;
}
export type Input<R extends Route> = {
	params: Static<R["params"]>;
	query: Static<R["query"]>;
	body: Static<R["body"]>;
};
export type Output<R extends Route> = Static<R["response"]>;
const toolParams = Type.Object({ toolId: Id }, { additionalProperties: false });
const operationParams = Type.Object({ id: Id }, { additionalProperties: false });
const get = { method: "GET", params: Empty, query: Empty, body: Empty, status: 200 } as const;
const post = { method: "POST", query: Empty, body: Empty, status: 202 } as const;
export const routes = {
	setupStatus: defineRoute({
		...get,
		path: "/api/setup",
		response: SetupStatus,
		summary: "Read saved chat setup without contacting providers.",
	}),
	setupStart: defineRoute({
		...post,
		params: Empty,
		path: "/api/setup",
		body: SetupStart,
		response: SetupState,
		status: 200,
		summary: "Host Guided setup from the shared configure wizard.",
	}),
	setupState: defineRoute({
		...get,
		params: operationParams,
		path: "/api/setup/:id",
		response: SetupState,
		summary: "Read the current setup prompt.",
	}),
	setupAnswer: defineRoute({
		...post,
		params: operationParams,
		path: "/api/setup/:id",
		body: SetupAnswer,
		response: SetupState,
		status: 200,
		summary: "Answer the current setup prompt.",
	}),
	setupCancel: defineRoute({
		...post,
		method: "DELETE",
		params: operationParams,
		path: "/api/setup/:id",
		response: SetupState,
		status: 200,
		summary: "Cancel setup before saving.",
	}),

	system: defineRoute({
		...get,
		path: "/api/system",
		response: SystemReport,
		summary: "Read-only doctor findings and the four resolved Clio paths",
	}),
	interop: defineRoute({
		...get,
		path: "/api/workspaces/:id/interop",
		params: operationParams,
		query: InteropQuery,
		response: Interop,
		summary: "All registered external agents and bounded resource discovery; probe=versions runs each --version",
	}),
	decideInterop: defineRoute({
		...post,
		status: 200,
		path: "/api/workspaces/:id/interop/decisions",
		params: operationParams,
		body: InteropDecision,
		response: InteropDecided,
		summary: "Accept or decline a proposed delegation peer; accepting adds its settings entry",
	}),
	library: defineRoute({
		...get,
		path: "/api/workspaces/:id/library",
		params: operationParams,
		response: LibraryInventory,
		summary: "Canonical library packages, installed copies and recipe resources",
	}),
	libraryPlan: defineRoute({
		...post,
		status: 200,
		path: "/api/workspaces/:id/library/plans",
		params: operationParams,
		body: LibraryPlanRequest,
		response: LibraryPlan,
		summary: "Stage one reviewed library lifecycle plan; writes nothing",
	}),
	libraryPlanApply: defineRoute({
		...post,
		status: 200,
		path: "/api/workspaces/:id/library/plans/:planId/apply",
		params: LibraryPlanParams,
		response: LibraryApplyResult,
		summary: "Apply the exact plan that was reviewed and report per-package outcomes",
	}),
	libraryPlanRelease: defineRoute({
		...post,
		method: "DELETE",
		status: 200,
		path: "/api/workspaces/:id/library/plans/:planId",
		params: LibraryPlanParams,
		response: LibraryPlanReleased,
		summary: "Cancel a staged plan and release its sources",
	}),
	libraryExtensions: defineRoute({
		...get,
		path: "/api/workspaces/:id/library/extensions",
		params: operationParams,
		response: LibraryExtensions,
		summary: "Installed extensions and admission state",
	}),
	libraryAgents: defineRoute({
		...get,
		path: "/api/workspaces/:id/library/agents",
		params: operationParams,
		response: LibraryAgents,
		summary: "Resolved user-facing agent specifications",
	}),
	libraryVerifiers: defineRoute({
		...get,
		path: "/api/workspaces/:id/library/verifiers",
		params: operationParams,
		response: LibraryVerifiers,
		summary: "Verifier discovery without executing checks",
	}),
	usage: defineRoute({
		...get,
		path: "/api/workspaces/:id/usage",
		params: operationParams,
		response: UsageReport,
		summary: "Canonical usage report for the last 30 days",
	}),
	evidenceList: defineRoute({
		...get,
		path: "/api/evidence",
		query: FleetPageQuery,
		response: EvidencePage,
		summary: "Paginated evidence artifacts and trust verdicts",
	}),
	evidenceDetail: defineRoute({
		...get,
		path: "/api/evidence/:id",
		params: operationParams,
		response: EvidenceDetail,
		summary: "Evidence findings, canonical trust, admitted provenance and gate decisions",
	}),
	evidenceBuild: defineRoute({
		...post,
		path: "/api/workspaces/:id/evidence/:runId/build",
		params: Type.Object({ id: Id, runId: Id }, { additionalProperties: false }),
		response: Accepted,
		summary: "Collect evidence for a run through Clio",
	}),
	receiptVerify: defineRoute({
		...post,
		path: "/api/workspaces/:id/receipts/:runId/verify",
		params: Type.Object({ id: Id, runId: Id }, { additionalProperties: false }),
		response: Accepted,
		summary: "Recheck receipt integrity against its run through Clio",
	}),
	fleetRoots: defineRoute({
		...get,
		path: "/api/fleet/runs",
		response: FleetRoots,
		summary: "Paginated durable fleet roots",
		query: FleetPageQuery,
	}),
	fleetRoot: defineRoute({
		...get,
		path: "/api/fleet/runs/:id",
		response: FleetRootDetail,
		summary: "Fleet plan results, receipt and related topology",
		params: operationParams,
	}),
	dispatchRuns: defineRoute({
		...get,
		path: "/api/fleet/dispatches",
		response: DispatchRuns,
		summary: "Paginated durable dispatch runs",
		query: FleetPageQuery,
	}),
	dispatchRun: defineRoute({
		...get,
		path: "/api/fleet/dispatches/:id",
		response: DispatchRun,
		summary: "One durable dispatch run",
		params: operationParams,
	}),
	fleetReceipt: defineRoute({
		...get,
		path: "/api/fleet/receipts/:id",
		response: FleetReceipt,
		summary: "Full durable receipt by run identifier",
		params: operationParams,
	}),
	fleetCouncils: defineRoute({
		...get,
		path: "/api/fleet/councils",
		response: Councils,
		summary: "Canonical bounded council topology",
	}),
	fleetGates: defineRoute({
		...get,
		path: "/api/fleet/gates",
		response: FleetGates,
		summary: "Canonical verified gate decision topology",
	}),

	targetsList: defineRoute({
		...get,
		path: "/api/workspaces/:id/targets",
		params: operationParams,
		response: CliTargets,
		summary: "Configured targets through the canonical CLI",
	}),
	routing: defineRoute({
		...get,
		path: "/api/workspaces/:id/routing",
		params: operationParams,
		response: Routing,
		summary: "Offline models, fleet profiles and agent bindings",
	}),
	targetsProbe: defineRoute({
		...post,
		path: "/api/workspaces/:id/targets/:targetId/probe",
		params: Type.Object({ id: Id, targetId: Id }, { additionalProperties: false }),
		response: Accepted,
		summary: "Probe configured targets and return this target's status",
	}),
	targetsUse: defineRoute({
		...post,
		path: "/api/workspaces/:id/targets/:targetId/use",
		params: Type.Object({ id: Id, targetId: Id }, { additionalProperties: false }),
		response: Accepted,
		summary: "Use a target for chat and fleet through the CLI",
	}),
	targetsRemove: defineRoute({
		...post,
		path: "/api/workspaces/:id/targets/:targetId/remove",
		params: Type.Object({ id: Id, targetId: Id }, { additionalProperties: false }),
		response: Accepted,
		summary: "Remove a configured target through the CLI",
	}),
	workspaceSettings: defineRoute({
		...get,
		path: "/api/workspaces/:id/settings",
		params: operationParams,
		response: SettingsReport,
		summary: "Effective settings and each leaf's origin layer",
	}),
	settingsControls: defineRoute({
		...get,
		path: "/api/workspaces/:id/settings/controls",
		params: operationParams,
		response: SettingsControls,
		summary: "The engine's setting controls with the app's write policy, timing and origin",
	}),
	writeSetting: defineRoute({
		...post,
		method: "PATCH",
		status: 200,
		path: "/api/workspaces/:id/settings/controls",
		params: operationParams,
		body: SettingWrite,
		response: SettingWritten,
		summary: "Write one allowlisted setting to the user layer through the engine's cross-field validation",
	}),
	configGraph: defineRoute({
		...get,
		path: "/api/workspaces/:id/config-graph",
		params: operationParams,
		response: ConfigGraph,
		summary: "Read-only customization graph without secrets or hook argv",
	}),
	sessionInterview: defineRoute({
		...get,
		path: "/api/sessions/:id/interview",
		params: operationParams,
		response: Type.Union([InterviewRound, Type.Null()]),
		summary: "Pending operator interview when the ACP peer advertises support",
	}),
	answerInterview: defineRoute({
		...post,
		status: 200,
		path: "/api/sessions/:id/interview/:roundId",
		params: Type.Object({ id: Id, roundId: Id }, { additionalProperties: false }),
		body: InterviewSubmission,
		response: Empty,
		summary: "Submit this interview round's choices and text, or cancel it",
	}),
	permission: defineRoute({
		...post,
		status: 200,
		path: "/api/sessions/:id/permissions/:permissionId",
		params: Type.Object({ id: Id, permissionId: Id }, { additionalProperties: false }),
		body: Type.Object({ decision: PermissionDecision }, { additionalProperties: false }),
		response: Empty,
		summary: "Answer a pending permission once",
	}),
	cancelTurn: defineRoute({
		...post,
		status: 200,
		path: "/api/sessions/:id/turns/:turnId/cancel",
		params: Type.Object({ id: Id, turnId: Id }, { additionalProperties: false }),
		response: Empty,
		summary: "Cancel the specified active turn",
	}),
	// Mid-turn interaction. Every one of these rides a namespaced ACP method that
	// is additive to protocolVersion 1, so a session opened against an engine
	// that announced no `steering` capability answers 409 rather than 404: the
	// route exists, this peer just cannot serve it.
	sessionCapabilities: defineRoute({
		...get,
		path: "/api/sessions/:id/capabilities",
		params: operationParams,
		response: AgentCapabilities,
		summary: "What the ACP agent announced at initialize",
	}),
	steerSession: defineRoute({
		...post,
		status: 200,
		path: "/api/sessions/:id/steer",
		params: operationParams,
		body: SteerRequest,
		response: SteerResult,
		summary: "Queue operator guidance on the running turn",
	}),
	sessionQueue: defineRoute({
		...get,
		path: "/api/sessions/:id/queue",
		params: operationParams,
		response: QueueSnapshot,
		summary: "Steering and follow-up texts waiting on the engine",
	}),
	clearSessionQueue: defineRoute({
		...post,
		status: 200,
		path: "/api/sessions/:id/queue/clear",
		params: operationParams,
		response: QueueCleared,
		summary: "Drain both queues and hand the texts back to re-send",
	}),
	interruptSession: defineRoute({
		...post,
		status: 200,
		path: "/api/sessions/:id/interrupt",
		params: operationParams,
		body: InterruptRequest,
		response: InterruptResult,
		summary: "Cancel the running turn, or report why it cannot be",
	}),
	steerDispatchRun: defineRoute({
		...post,
		status: 200,
		path: "/api/sessions/:id/dispatch/steer",
		params: operationParams,
		body: DispatchSteerRequest,
		response: DispatchSteerResult,
		summary: "Queue guidance on, or abort, one running worker",
	}),
	sessionBoard: defineRoute({
		...get,
		path: "/api/sessions/:id/board",
		params: operationParams,
		response: SessionBoard,
		summary: "The operator's tasks, the session plan, its decisions and the memory tier",
	}),
	supersedeDecision: defineRoute({
		...post,
		status: 200,
		path: "/api/sessions/:id/decisions/supersede",
		params: operationParams,
		body: DecisionSupersedeRequest,
		response: DecisionSuperseded,
		summary: "Mark a decision superseded; a correction also returns the request that tells Clio Coder",
	}),
	proposeMemory: defineRoute({
		...post,
		status: 200,
		path: "/api/sessions/:id/memory/propose",
		params: operationParams,
		body: MemoryProposeRequest,
		response: MemoryProposed,
		summary: "Propose a task-bank entry as a durable memory candidate for review",
	}),
	sessionTree: defineRoute({
		...get,
		path: "/api/sessions/:id/tree",
		params: operationParams,
		response: SessionTree,
		summary: "The conversation's branches, as the terminal's /tree shows them",
	}),
	switchSessionBranch: defineRoute({
		...post,
		status: 200,
		path: "/api/sessions/:id/branch",
		params: operationParams,
		body: BranchRequest,
		response: BranchSwitched,
		summary: "Continue this conversation from an earlier turn; other branches are kept",
	}),
	forkSession: defineRoute({
		...post,
		status: 200,
		path: "/api/sessions/:id/fork",
		params: operationParams,
		body: BranchRequest,
		response: Forked,
		summary: "Start a new conversation from a turn; workspace files are not rewound",
	}),
	sessionExtensions: defineRoute({
		...get,
		path: "/api/sessions/:id/extensions",
		params: operationParams,
		response: SessionExtensions,
		summary: "The extensions this conversation loaded, in its own words",
	}),
	reloadSessionExtensions: defineRoute({
		...post,
		status: 200,
		path: "/api/sessions/:id/extensions/reload",
		params: operationParams,
		response: ExtensionReload,
		summary: "Reload this conversation's extensions and hooks together",
	}),
	sessionUsage: defineRoute({
		...get,
		path: "/api/sessions/:id/usage",
		params: operationParams,
		response: SessionUsage,
		summary: "This conversation's spend per provider and model, and each provider's quota",
	}),
	askAside: defineRoute({
		...post,
		status: 200,
		path: "/api/sessions/:id/aside/ask",
		params: operationParams,
		body: AsideAskRequest,
		response: AsideAnswer,
		summary: "Ask a side question that never enters the conversation (/btw)",
	}),
	draftAside: defineRoute({
		...post,
		status: 200,
		path: "/api/sessions/:id/aside/draft",
		params: operationParams,
		body: AsideDraftRequest,
		response: AsideDrafts,
		summary: "Draft answers in parallel and judge them, beside the conversation (/draft)",
	}),
	cancelAside: defineRoute({
		...post,
		status: 200,
		path: "/api/sessions/:id/aside/cancel",
		params: operationParams,
		response: AsideCancelled,
		summary: "Cancel the side question or draft that is running",
	}),
	sessionContext: defineRoute({
		...get,
		path: "/api/sessions/:id/context",
		params: operationParams,
		response: ContextLedger,
		summary: "The context window as Clio Coder accounts for it",
	}),
	previewFleetRun: defineRoute({
		...post,
		status: 200,
		path: "/api/sessions/:id/fleet/preview",
		params: operationParams,
		body: FleetPreviewRequest,
		response: FleetPreview,
		summary: "Compile a fleet contract for review; nothing is dispatched",
	}),
	startFleetRun: defineRoute({
		...post,
		status: 200,
		path: "/api/sessions/:id/fleet/run",
		params: operationParams,
		body: FleetRunRequest,
		response: FleetRunResult,
		summary: "Start a fleet contract only when its plan still hashes to the approved one",
	}),
	prepareHandoff: defineRoute({
		...post,
		status: 200,
		path: "/api/sessions/:id/handoff",
		params: operationParams,
		body: HandoffPrepareRequest,
		response: HandoffDraft,
		summary: "Draw up a handoff document for review; nothing is written",
	}),
	commitHandoff: defineRoute({
		...post,
		status: 200,
		path: "/api/sessions/:id/handoff/commit",
		params: operationParams,
		body: HandoffCommitRequest,
		response: HandoffCommitted,
		summary: "Start a new conversation from the reviewed handoff document",
	}),
	cancelHandoff: defineRoute({
		...post,
		status: 200,
		path: "/api/sessions/:id/handoff/cancel",
		params: operationParams,
		body: HandoffCancelRequest,
		response: HandoffCancelled,
		summary: "Discard a handoff document awaiting review",
	}),
	sessionCommands: defineRoute({
		...get,
		path: "/api/sessions/:id/commands",
		params: operationParams,
		response: CommandCatalog,
		summary: "The operator commands this agent exposes, with their grammar",
	}),
	invokeSessionCommand: defineRoute({
		...post,
		status: 200,
		path: "/api/sessions/:id/commands",
		params: operationParams,
		body: CommandRequest,
		response: CommandResult,
		summary: "Run one exposed operator command",
	}),
	sessionSettings: defineRoute({
		...get,
		path: "/api/sessions/:id/settings",
		params: operationParams,
		response: SafeSettings,
		summary: "The four ACP safe settings",
	}),
	setSessionConfig: defineRoute({
		...post,
		status: 200,
		path: "/api/sessions/:id/config",
		params: operationParams,
		body: SetConfigOption,
		response: SessionConfig,
		summary: "Choose a reported model or thinking level for this conversation",
	}),
	patchSessionSettings: defineRoute({
		...post,
		method: "PATCH",
		status: 200,
		path: "/api/sessions/:id/settings",
		params: operationParams,
		body: SafeSettingsPatch,
		response: SafeSettings,
		summary: "Patch only the four ACP safe settings",
	}),
	sessionTargets: defineRoute({
		...get,
		path: "/api/sessions/:id/targets",
		params: operationParams,
		response: SessionTargets,
		summary: "Targets available to this ACP session",
	}),
	probeSessionTarget: defineRoute({
		...post,
		status: 200,
		path: "/api/sessions/:id/targets/:targetId/probe",
		params: Type.Object({ id: Id, targetId: Id }, { additionalProperties: false }),
		response: TargetProbe,
		summary: "Probe a configured target through ACP",
	}),
	labelSession: defineRoute({
		...post,
		method: "PATCH",
		status: 200,
		path: "/api/sessions/:id",
		params: operationParams,
		body: Type.Object(
			{ label: Type.String({ maxLength: 256, pattern: "^[^\\u0000-\\u001f\\u007f]*$" }), workspaceId: Type.Optional(Id) },
			{ additionalProperties: false },
		),
		response: Empty,
		summary: "Save the session label through ACP",
	}),
	deleteSession: defineRoute({
		...post,
		method: "DELETE",
		status: 200,
		path: "/api/sessions/:id",
		params: operationParams,
		body: Type.Object({ workspaceId: Type.Optional(Id) }, { additionalProperties: false }),
		response: Empty,
		summary: "Delete a closed session through ACP",
	}),
	sessionAutonomy: defineRoute({
		...get,
		path: "/api/sessions/:id/autonomy",
		params: operationParams,
		response: Autonomy,
		summary: "Current session autonomy and source",
	}),
	setSessionAutonomy: defineRoute({
		...post,
		status: 200,
		path: "/api/sessions/:id/autonomy",
		params: operationParams,
		body: Type.Object({ level: AutonomyLevel }, { additionalProperties: false }),
		response: Autonomy,
		summary: "Set autonomy for this session",
	}),
	workspaces: defineRoute({
		...get,
		path: "/api/workspaces",
		response: Type.Array(Workspace),
		summary: "Recent workspaces",
	}),
	workspacePathComplete: defineRoute({
		...get,
		path: "/api/workspaces/complete",
		query: Type.Object(
			{
				input: Type.String({ maxLength: 4096 }),
				hidden: Type.Optional(Type.Boolean()),
			},
			{ additionalProperties: false },
		),
		response: PathCompletion,
		summary: "Complete a typed directory path on this machine",
	}),
	workspacePick: defineRoute({
		...post,
		status: 200,
		params: Empty,
		path: "/api/workspaces/pick",
		response: WorkspacePick,
		summary: "Ask the operating system's folder dialog for a workspace directory",
	}),
	openWorkspace: defineRoute({
		...post,
		status: 200,
		params: Empty,
		path: "/api/workspaces",
		body: Type.Object({ path: Type.String({ minLength: 1, maxLength: 4096 }) }, { additionalProperties: false }),
		response: Workspace,
		summary: "Open an existing workspace by absolute path",
	}),
	workspace: defineRoute({
		...get,
		params: operationParams,
		path: "/api/workspaces/:id",
		response: Workspace,
		summary: "Canonical workspace",
	}),
	sessionHistory: defineRoute({
		...get,
		params: operationParams,
		path: "/api/workspaces/:id/sessions",
		response: Type.Array(SessionSummary),
		summary: "Durable session history without starting a child",
	}),
	newSession: defineRoute({
		...post,
		status: 200,
		params: operationParams,
		path: "/api/workspaces/:id/sessions",
		response: SessionSnapshot,
		summary: "Start a supervised ACP session",
	}),
	loadSession: defineRoute({
		...post,
		status: 200,
		params: operationParams,
		path: "/api/sessions/:id/load",
		body: Type.Object({ workspaceId: Id }, { additionalProperties: false }),
		response: SessionSnapshot,
		summary: "Load a durable session and project its replay",
	}),
	sessions: defineRoute({
		...get,
		path: "/api/sessions",
		response: Type.Array(SessionSnapshot),
		summary: "Sessions supervised or recovered by this server",
	}),
	session: defineRoute({
		...get,
		params: operationParams,
		path: "/api/sessions/:id",
		response: SessionSnapshot,
		summary: "Session projection snapshot",
	}),
	turn: defineRoute({
		...post,
		params: operationParams,
		path: "/api/sessions/:id/turns",
		body: Type.Object(
			{
				text: Type.String({ minLength: 1, maxLength: 32000, pattern: "\\S" }),
				images: Type.Optional(Type.Array(TurnImage, { minItems: 1, maxItems: TURN_IMAGE_MAX })),
				files: Type.Optional(Type.Array(TurnFile, { minItems: 1, maxItems: TURN_FILE_MAX })),
			},
			{ additionalProperties: false },
		),
		response: Type.Object({ turnId: Id }, { additionalProperties: false }),
		summary: "Start a streamed turn, with any images and text files the request carries",
	}),
	closeSession: defineRoute({
		...post,
		status: 200,
		params: operationParams,
		path: "/api/sessions/:id/close",
		response: SessionSnapshot,
		summary: "Close the supervised session and its child",
	}),
	traceStatus: defineRoute({
		...get,
		path: "/api/traces/status",
		response: TraceStatus,
		summary: "Trace availability and retention",
	}),
	traceRuns: defineRoute({
		...get,
		path: "/api/traces/runs",
		query: TraceRunsQuery,
		response: TraceRunsPage,
		summary: "Paginated trace history",
	}),
	traceRun: defineRoute({
		...get,
		path: "/api/traces/runs/:runId",
		params: TraceParams,
		response: TraceRun,
		summary: "Trace run",
	}),
	tracePhases: defineRoute({
		...get,
		path: "/api/traces/runs/:runId/phases",
		params: TraceParams,
		response: Type.Array(TracePhase),
		summary: "Run phases",
	}),
	traceGates: defineRoute({
		...get,
		path: "/api/traces/runs/:runId/gates",
		params: TraceParams,
		response: Type.Array(TraceGate),
		summary: "Run gates",
	}),
	traceProcesses: defineRoute({
		...get,
		path: "/api/traces/runs/:runId/processes",
		params: TraceParams,
		response: Type.Array(TraceProcess),
		summary: "Run processes",
	}),
	traceEvents: defineRoute({
		...get,
		path: "/api/traces/runs/:runId/events",
		params: TraceParams,
		query: TraceEventsQuery,
		response: TraceEventsPage,
		summary: "Run events by rowid",
	}),
	traceReceipt: defineRoute({
		...get,
		path: "/api/traces/runs/:runId/receipt",
		params: TraceParams,
		query: Type.Object({ include: Type.Optional(Type.Literal("full")) }, { additionalProperties: false }),
		response: TraceReceipt,
		summary: "Receipt and evidence summary; full payload on request",
	}),
	traceLive: defineRoute({
		...get,
		path: "/api/traces/runs/:runId/live",
		params: TraceParams,
		query: Type.Object(
			{ after: Type.Optional(RowCursor), token: Type.Optional(Type.String({ maxLength: 256 })) },
			{ additionalProperties: false },
		),
		response: Type.String(),
		stream: true,
		summary: "Live rowid event tail",
	}),
	meta: defineRoute({ ...get, path: "/api/meta", response: Meta, summary: "Application and Clio versions" }),
	openapi: defineRoute({
		...get,
		path: "/api/openapi.json",
		response: Type.Record(Type.String(), Type.Unknown()),
		summary: "OpenAPI contract",
	}),
	events: defineRoute({
		...get,
		path: "/api/events",
		query: Type.Object(
			{ after: Type.Optional(EventCursor), token: Type.Optional(Type.String({ maxLength: 256 })) },
			{ additionalProperties: false },
		),
		response: Type.String(),
		stream: true,
		summary: "Global event stream",
	}),
	tools: defineRoute({
		...get,
		path: "/api/toolchain/tools",
		response: Tools,
		summary: "Pinned tools in registry order",
	}),
	install: defineRoute({
		...post,
		path: "/api/toolchain/tools/:toolId/install",
		params: toolParams,
		body: Install,
		response: Accepted,
		summary: "Install the pinned tool",
	}),
	remove: defineRoute({
		...post,
		path: "/api/toolchain/tools/:toolId/remove",
		params: toolParams,
		response: Accepted,
		summary: "Remove vendored versions",
	}),
	operation: defineRoute({
		...get,
		path: "/api/operations/:id",
		params: operationParams,
		response: Operation,
		summary: "Operation snapshot",
	}),
	cancel: defineRoute({
		...post,
		status: 200,
		path: "/api/operations/:id/cancel",
		params: operationParams,
		response: Operation,
		summary: "Cancel a cancellable operation",
	}),
};
