import { deepStrictEqual, doesNotMatch, match, ok, strictEqual } from "node:assert/strict";
import { mkdirSync } from "node:fs";
import { join } from "node:path";
import { afterEach, beforeEach, it } from "node:test";
import { setImmediate as nextTick } from "node:timers/promises";
import { DEFAULT_SETTINGS } from "../../src/core/defaults.js";
import { deliverPeerPrompt, PEER_INBOX_TOKEN } from "../../src/domains/mux/peer-inbox.js";
import type { ProvidersContract } from "../../src/domains/providers/index.js";
import { EMPTY_CAPABILITIES } from "../../src/domains/providers/index.js";
import { createSessionBundle } from "../../src/domains/session/extension.js";
import type { SessionEntry } from "../../src/domains/session/index.js";
import { isSessionEntry, isSessionHeader } from "../../src/domains/session/index.js";
import { registerEngineFauxProvider } from "../../src/engine/api-registry.js";
import { readSessionFileEntries, sessionPaths } from "../../src/engine/session.js";
import { stripTerminalSequences, visibleWidth } from "../../src/engine/tui.js";
import { createChatPanel } from "../../src/interactive/chat-panel.js";
import { rehydrateChatPanelFromTurns } from "../../src/interactive/chat-renderer.js";
import { createPeerInbox } from "../../src/interactive/peer-inbox.js";
import type { ChatLoopEvent, CreateChatLoopDeps } from "../../src/session-control/chat-loop.js";
import { createChatLoop } from "../../src/session-control/chat-loop.js";
import { dispatchStubContext } from "../harness/dispatch-stub-context.js";
import type { IsolatedClioEnv } from "../harness/scratch-env.js";
import { isolateClioEnv } from "../harness/scratch-env.js";

const TYPED = "/wtfp:create-poster SSH fleet architecture";
const EXPANDED =
	"<!-- Generated by WTF-P adapter compiler v5 from protocol/actions/create-poster; do not edit. -->\n\n# Create a poster\n\nSSH fleet architecture";

let env: IsolatedClioEnv;
let previousCwd: string;

beforeEach(async () => {
	env = await isolateClioEnv("title-typed-");
	previousCwd = process.cwd();
	const project = join(env.dir, "project");
	mkdirSync(project);
	process.chdir(project);
});
afterEach(() => {
	process.chdir(previousCwd);
	env.restore();
});

it("titles a session from the typed input when a prompt template expanded it", async () => {
	const settings = structuredClone(DEFAULT_SETTINGS);
	settings.chat.prewarm = false;
	const context = dispatchStubContext({ settings });
	const target = settings.targets[0];
	ok(target);
	settings.chat.target = target.id;
	settings.chat.model = target.defaultModel ?? "gpt-4o";
	const session = createSessionBundle(context).contract;
	const prompted: string[] = [];
	const entries = (): SessionEntry[] => {
		const meta = session.current();
		if (!meta) return [];
		return readSessionFileEntries(sessionPaths(meta).current).filter(
			(entry): entry is SessionEntry => !isSessionHeader(entry) && isSessionEntry(entry),
		);
	};
	const loop = createChatLoop({
		getSettings: () => settings,
		providers: context.getContract<ProvidersContract>("providers") as ProvidersContract,
		knownTargets: () => new Set([target.id]),
		session,
		readSessionEntries: entries,
		createAgent: ((options: Parameters<NonNullable<CreateChatLoopDeps["createAgent"]>>[0]) => ({
			agent: {
				state: options?.initialState,
				subscribe: () => () => {},
				abort: () => {},
				prompt: async (text: string) => {
					prompted.push(text);
				},
			},
		})) as unknown as NonNullable<CreateChatLoopDeps["createAgent"]>,
	});
	let token: string | null = null;
	const inbox = createPeerInbox({
		bus: context.bus,
		mux: {
			mode: "guest",
			detection: () => ({ self: { paneId: "w1:p2" }, socketPath: "/owned.sock" }),
			advertiseSelfToken: async (key: string, value: string | null) => {
				if (key === PEER_INBOX_TOKEN) token = value;
				return true;
			},
		} as never,
		chat: loop,
		stateDir: join(env.dir, "state"),
		showTurn: () => {},
	});
	try {
		await nextTick();
		const initial = token;
		ok(initial);
		strictEqual(session.current(), null);
		loop.resetForSession(null);
		await nextTick();
		strictEqual(token === initial, false, "an explicit empty /new retires the initial generation");
		const afterReset = token;
		const stale = await deliverPeerPrompt({
			stateDir: join(env.dir, "state"),
			token: initial,
			paneId: "w1:p2",
			socketPath: "/owned.sock",
			fromPaneId: "w1:p1",
			text: "for the retired empty conversation",
			timeoutMs: 300,
		});
		strictEqual(stale.status, "not-delivered");
		strictEqual(session.current(), null, "stale delivery cannot create the new conversation");
		strictEqual(prompted.length, 0);
		await loop.submit(EXPANDED, { display: { text: TYPED, note: "expanded prompt template create-poster" } });
		await nextTick();
		strictEqual(token, afterReset, "ordinary first-turn creation keeps the advertised generation");
		strictEqual(prompted.length, 1);
		ok(prompted[0]?.includes("# Create a poster"), "the model still receives the expanded template");

		const user = entries().find((entry) => entry.kind === "message" && entry.role === "user");
		ok(user && user.kind === "message");
		const payload = user.payload as { text: string; operatorText?: string; displayText?: string };
		strictEqual(payload.displayText, TYPED);
		// Compaction reasserts the operator's request from these fields, so the
		// expansion must survive in them.
		ok((payload.operatorText ?? payload.text).includes("# Create a poster"));

		strictEqual(session.history()[0]?.firstMessagePreview, TYPED);

		const panel = createChatPanel({ getOutputStyle: () => "detailed" });
		rehydrateChatPanelFromTurns(panel, entries());
		const replay = panel.render(120).join("\n");
		ok(replay.includes(TYPED), replay);
		ok(!replay.includes("Generated by WTF-P adapter compiler"), replay);

		// A turn another Clio submitted keeps its origin in the ledger, so a
		// replay still says the operator did not type it.
		const origin = "machine prompt from Clio in pane w1:p1";
		await loop.submit("review the diff", { origin });
		const origins = entries()
			.filter((entry) => entry.kind === "message" && entry.role === "user")
			.map((entry) => ("payload" in entry ? (entry.payload as { origin?: string }).origin : undefined));
		deepStrictEqual(origins, [undefined, origin]);
		const replayed = createChatPanel({ getOutputStyle: () => "detailed" });
		rehydrateChatPanelFromTurns(replayed, entries());
		ok(replayed.render(120).join("\n").includes(origin));
	} finally {
		inbox?.dispose();
		loop.dispose();
		await loop.whenSettled();
		await session.close();
	}
});

it("persists and replays machine origin after the real engine injects a busy follow-up", {
	timeout: 10_000,
}, async () => {
	const faux = registerEngineFauxProvider({
		api: "peer-origin-fixture",
		models: [{ id: "peer-model" }],
		tokensPerSecond: 0,
	});
	const model = faux.getModel();
	const providerUsers: string[] = [];
	let release!: () => void;
	const gate = new Promise<void>((resolve) => {
		release = resolve;
	});
	let entered!: () => void;
	const started = new Promise<void>((resolve) => {
		entered = resolve;
	});
	const response: Parameters<typeof faux.setResponses>[0][number] = async (_context, _options, state) => {
		providerUsers.push(JSON.stringify(_context.messages.filter((message) => message.role === "user")));
		if (state.callCount === 1) {
			entered();
			await gate;
		}
		return {
			role: "assistant",
			content: [{ type: "text", text: "finished" }],
			api: model.api,
			provider: model.provider,
			model: model.id,
			timestamp: Date.now(),
			stopReason: "stop",
			usage: {
				input: 0,
				output: 0,
				cacheRead: 0,
				cacheWrite: 0,
				totalTokens: 0,
				cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0, total: 0 },
			},
		};
	};
	faux.setResponses([response, response, response, response]);
	const settings = structuredClone(DEFAULT_SETTINGS);
	settings.chat.prewarm = false;
	settings.targets = [{ id: "peer-target", runtime: "peer-fixture", defaultModel: model.id }];
	settings.chat.target = "peer-target";
	settings.chat.model = model.id;
	const context = dispatchStubContext({
		settings,
		runtime: {
			id: "peer-fixture",
			displayName: "Fixture",
			kind: "http",
			apiFamily: "openai-completions",
			auth: "none",
			defaultCapabilities: { ...EMPTY_CAPABILITIES, chat: true, tools: true, contextWindow: 32768, maxTokens: 4096 },
			synthesizeModel: () => model,
		},
	});
	const session = createSessionBundle(context).contract;
	const entries = (): SessionEntry[] => {
		const meta = session.current();
		return meta
			? readSessionFileEntries(sessionPaths(meta).current).filter(
					(entry): entry is SessionEntry => !isSessionHeader(entry) && isSessionEntry(entry),
				)
			: [];
	};
	const loop = createChatLoop({
		getSettings: () => settings,
		providers: context.getContract<ProvidersContract>("providers") as ProvidersContract,
		knownTargets: () => new Set(["peer-target"]),
		session,
		readSessionEntries: entries,
	});
	const live = createChatPanel({ getOutputStyle: () => "detailed" });
	const queued: Array<Extract<ChatLoopEvent, { type: "queued_user_turn" }>> = [];
	loop.onEvent((event) => {
		live.applyEvent(event);
		if (event.type === "queued_user_turn") queued.push(event);
	});
	try {
		live.appendUser("operator turn");
		const running = loop.submit("operator turn");
		await started;
		strictEqual(loop.isStreaming(), true);
		const text = "review the diff after this turn";
		const origin = "machine prompt from Clio in pane w1:p1";
		strictEqual(loop.queueFollowUp(text, { text, note: origin }, origin), true);
		strictEqual(
			entries().filter((entry) => entry.kind === "message" && entry.role === "user").length,
			1,
			"enqueue alone must not manufacture a durable user turn",
		);
		release();
		await running;
		await loop.whenSettled();
		strictEqual(faux.state.callCount, 2, "Pi consumed the follow-up in the active run");
		deepStrictEqual(loop.queuedMessages(), { steer: [], followUp: [] });
		const users = entries().filter((entry) => entry.kind === "message" && entry.role === "user");
		deepStrictEqual(
			users.map((entry) => (entry as { payload: { text: string; origin?: string } }).payload),
			[{ text: "operator turn" }, { text, origin }],
		);
		const panel = createChatPanel({ getOutputStyle: () => "detailed" });
		rehydrateChatPanelFromTurns(panel, entries());
		const replay = panel.render(120).join("\n");
		ok(replay.includes(text), replay);
		ok(replay.includes(origin), replay);
		strictEqual(queued[0]?.origin, origin, "queue injection retains machine provenance");
		strictEqual(
			live.render(120).map(stripTerminalSequences).join("\n").split(origin).length - 1,
			1,
			"peer origin is shown once when its display note is the same attribution",
		);

		// A lifecycle change during an admission await retires the sender's
		// generation before persistence or another model request can happen.
		let current = true;
		let admitted = false;
		await loop.submit("retired generation prompt", {
			origin,
			isAdmissionCurrent: () => current,
			onPreparationVisible: async () => {
				current = false;
			},
			onAdmitted: () => {
				admitted = true;
			},
		});
		strictEqual(admitted, false);
		strictEqual(faux.state.callCount, 2, "retired admission never reaches the model");
		deepStrictEqual(
			entries().filter((entry) => entry.kind === "message" && entry.role === "user"),
			users,
			"retired admission appends no user row",
		);
		for (const [executionId, text] of [
			["occurrence-1", "Inspect the build"],
			["delivery-1", "Analyze the matching build"],
		] as const) {
			const origin = `job job-watch ${executionId}`;
			const result = await loop.submitMachineTurn?.({
				jobId: "job-watch",
				executionId,
				text,
				origin,
				sessionId: session.current()?.id ?? "",
				signal: new AbortController().signal,
				isAdmissionCurrent: () => true,
				onStarting: () => true,
			});
			strictEqual(result?.status, "succeeded");
			const event = queued.at(-1);
			ok(event);
			strictEqual(event.origin, origin);
			const entry = entries().find(
				(entry) =>
					entry.kind === "message" && entry.role === "user" && (entry.payload as { origin?: string }).origin === origin,
			);
			ok(entry?.kind === "message");
			strictEqual(entry.role, "user", "scheduled input keeps the model's user role");
			ok(providerUsers.at(-1)?.includes(text), "the provider receives the scheduled task");
			for (const style of ["compact", "standard", "detailed"] as const) {
				const projected = createChatPanel({ getOutputStyle: () => style });
				projected.applyEvent(event);
				const resumed = createChatPanel({ getOutputStyle: () => style });
				rehydrateChatPanelFromTurns(resumed, [entry]);
				for (const width of [20, 40, 80, 120]) {
					const raw = projected.render(width);
					const plain = raw.map(stripTerminalSequences).join("\n");
					deepStrictEqual(raw.map(stripTerminalSequences), resumed.render(width).map(stripTerminalSequences));
					match(plain, /Scheduled loop/u);
					ok(plain.includes("job-watch"));
					doesNotMatch(plain, /▌/u);
					ok(!raw.join("\n").includes("\x1b]133;A"), "scheduled prompts are not operator navigation markers");
					ok(raw.every((row) => visibleWidth(row) <= width));
				}
			}
		}
		match(live.render(120).map(stripTerminalSequences).join("\n"), /▌ operator turn/u);
	} finally {
		release();
		loop.dispose();
		await loop.whenSettled();
		await session.close();
		faux.unregister();
	}
});
