import { ok, strictEqual } from "node:assert/strict";
import { mkdirSync } from "node:fs";
import { join } from "node:path";
import { afterEach, beforeEach, it } from "node:test";
import { DEFAULT_SETTINGS } from "../../src/core/defaults.js";
import type { ProvidersContract } from "../../src/domains/providers/index.js";
import { createSessionBundle } from "../../src/domains/session/extension.js";
import { isSessionEntry, isSessionHeader, type SessionEntry } from "../../src/domains/session/index.js";
import { readSessionFileEntries, sessionPaths } from "../../src/engine/session.js";
import { type CreateChatLoopDeps, createChatLoop } from "../../src/interactive/chat-loop.js";
import { createChatPanel } from "../../src/interactive/chat-panel.js";
import { rehydrateChatPanelFromTurns } from "../../src/interactive/chat-renderer.js";
import { dispatchStubContext } from "../harness/dispatch-stub-context.js";
import { type IsolatedClioEnv, isolateClioEnv } from "../harness/scratch-env.js";

const TYPED = "/wtfp:create-poster SSH fleet architecture";
const EXPANDED =
	"<!-- Generated by WTF-P adapter compiler v5 from protocol/actions/create-poster; do not edit. -->\n\n# Create a poster\n\nSSH fleet architecture";

let env: IsolatedClioEnv;
let previousCwd: string;

beforeEach(async () => {
	env = await isolateClioEnv("title-typed-");
	previousCwd = process.cwd();
	const project = join(env.dir, "project");
	mkdirSync(project);
	process.chdir(project);
});
afterEach(() => {
	process.chdir(previousCwd);
	env.restore();
});

it("titles a session from the typed input when a prompt template expanded it", async () => {
	const settings = structuredClone(DEFAULT_SETTINGS);
	settings.chat.prewarm = false;
	const context = dispatchStubContext({ settings });
	const target = settings.targets[0];
	ok(target);
	settings.chat.target = target.id;
	settings.chat.model = target.defaultModel ?? "gpt-4o";
	const session = createSessionBundle(context).contract;
	const prompted: string[] = [];
	const entries = (): SessionEntry[] => {
		const meta = session.current();
		if (!meta) return [];
		return readSessionFileEntries(sessionPaths(meta).current).filter(
			(entry): entry is SessionEntry => !isSessionHeader(entry) && isSessionEntry(entry),
		);
	};
	const loop = createChatLoop({
		getSettings: () => settings,
		providers: context.getContract<ProvidersContract>("providers") as ProvidersContract,
		knownTargets: () => new Set([target.id]),
		session,
		readSessionEntries: entries,
		createAgent: ((options: Parameters<NonNullable<CreateChatLoopDeps["createAgent"]>>[0]) => ({
			agent: {
				state: options?.initialState,
				subscribe: () => () => {},
				abort: () => {},
				prompt: async (text: string) => {
					prompted.push(text);
				},
			},
		})) as unknown as NonNullable<CreateChatLoopDeps["createAgent"]>,
	});
	try {
		await loop.submit(EXPANDED, { display: { text: TYPED, note: "expanded prompt template create-poster" } });
		strictEqual(prompted.length, 1);
		ok(prompted[0]?.includes("# Create a poster"), "the model still receives the expanded template");

		const user = entries().find((entry) => entry.kind === "message" && entry.role === "user");
		ok(user && user.kind === "message");
		const payload = user.payload as { text: string; operatorText?: string; displayText?: string };
		strictEqual(payload.displayText, TYPED);
		// Compaction reasserts the operator's request from these fields, so the
		// expansion must survive in them.
		ok((payload.operatorText ?? payload.text).includes("# Create a poster"));

		strictEqual(session.history()[0]?.firstMessagePreview, TYPED);

		const panel = createChatPanel({ getOutputStyle: () => "detailed" });
		rehydrateChatPanelFromTurns(panel, entries());
		const replay = panel.render(120).join("\n");
		ok(replay.includes(TYPED), replay);
		ok(!replay.includes("Generated by WTF-P adapter compiler"), replay);
	} finally {
		loop.dispose();
		await loop.whenSettled();
		await session.close();
	}
});
