/**
 * Public surface of the local stdio MCP module: protocol framing, the
 * one-process client, strict configuration loading, and explicit trust.
 */

export {
	createMcpStdioClient,
	DEFAULT_INITIALIZE_TIMEOUT_MS,
	DEFAULT_KILL_GRACE_MS,
	DEFAULT_MAX_OUTBOUND_BYTES,
	DEFAULT_MCP_CLIENT_VERSION,
	DEFAULT_REQUEST_TIMEOUT_MS,
	DEFAULT_RESULT_TEXT_BYTES,
	DEFAULT_STDERR_TAIL_BYTES,
	DEFAULT_TEARDOWN_BOUND_MS,
	MCP_CLIENT_NAME,
	MCP_TOOL_LIST_CAP,
	type McpCallToolOptions,
	type McpClient,
	type McpClientOptions,
	type McpClientState,
	type McpClientStatus,
	type McpContentBlock,
	type McpServerInfo,
	type McpServerSpec,
	type McpTeardownOutcome,
	type McpToolCallResult,
	type McpToolDescriptor,
	type McpToolListing,
	renderMcpContent,
} from "./client.js";
export {
	loadMcpServerConfig,
	MCP_CONFIG_CAPS,
	MCP_CONFIG_VERSION,
	MCP_PROJECT_CONFIG_RELATIVE_PATH,
	MCP_USER_CONFIG_FILENAME,
	type McpConfigDiagnostic,
	type McpConfigLoadOptions,
	type McpConfigLoadResult,
	type McpConfigTextInput,
	type McpServerDeclaration,
	type McpServerScope,
	mcpConfigPaths,
	mcpServerDigest,
	parseMcpConfigText,
} from "./config.js";
export {
	classifyJsonRpcMessage,
	createLineFramer,
	DEFAULT_MAX_LINE_BYTES,
	encodeJsonRpcMessage,
	JSON_RPC_METHOD_NOT_FOUND,
	type JsonRpcErrorObject,
	type JsonRpcId,
	type JsonRpcMessage,
	type JsonRpcNotification,
	type JsonRpcRequest,
	type JsonRpcResponse,
	type LineFramer,
	MCP_PROTOCOL_VERSION,
	McpError,
	type McpErrorCode,
	type ProtocolFrame,
	parseJsonRpcLine,
} from "./protocol.js";
export {
	MCP_TRUST_ACTION_CLASSES,
	MCP_TRUST_CAPS,
	MCP_TRUST_FILENAME,
	MCP_TRUST_VERSION,
	type McpTrustActionClass,
	type McpTrustOptions,
	type McpTrustReadResult,
	type McpTrustRecord,
	type McpTrustState,
	type McpTrustStatus,
	mcpTrustPath,
	type ResolvedMcpServer,
	type ResolvedMcpServers,
	readMcpTrustState,
	resolveMcpServers,
	type TrustMcpServerOptions,
	type TrustMcpServerResult,
	trustMcpServer,
	type UntrustMcpServerResult,
	untrustMcpServer,
} from "./trust.js";
