import { tokenHex } from "../../../core/theme-token-hex.js";

/** Render the deliberately small Clio overlay on Yazi's pinned preset theme. */
export function renderYaziTheme(): string {
	return `# Generated by Clio Coder. Changes are replaced when the managed profile regenerates.

[mgr]
cwd = { fg = "${tokenHex("accent")}" }
find_keyword = { fg = "${tokenHex("warning")}" }
marker_selected = { fg = "${tokenHex("success")}", bg = "${tokenHex("success")}" }
marker_copied = { fg = "${tokenHex("accent")}", bg = "${tokenHex("accent")}" }
marker_cut = { fg = "${tokenHex("error")}", bg = "${tokenHex("error")}" }
border_style = { fg = "${tokenHex("frame")}" }

[mode]
normal_main = { bg = "${tokenHex("accent")}" }
normal_alt = { fg = "${tokenHex("accent")}" }
select_main = { bg = "${tokenHex("action")}" }
select_alt = { fg = "${tokenHex("action")}" }
unset_main = { bg = "${tokenHex("error")}" }
unset_alt = { fg = "${tokenHex("error")}" }

[tabs]
active = { bg = "${tokenHex("accent")}" }
inactive = { fg = "${tokenHex("accent")}" }

[status]
perm_sep = { fg = "${tokenHex("dim")}" }
`;
}
