import { tokenHex } from "../../../core/theme-token-hex.js";

/**
 * Render the Clio overlay on Yazi's pinned preset theme.
 *
 * Every color comes from Clio's own token palette (`core/theme-token-hex.ts`),
 * read when the managed profile is generated, which happens on the open that
 * finds no current profile. The profile stamp carries this file's output hash,
 * so a palette change regenerates the profile on the next open rather than
 * leaving a pane in last release's colors. Only keys Yazi 26.8 documents are
 * set; the rest of the preset stays, because a wrong key here is rejected by
 * the validation open in `profile.ts` and would leave the operator with no
 * files pane at all.
 */
export function renderYaziTheme(): string {
	const accent = tokenHex("accent");
	const action = tokenHex("action");
	const success = tokenHex("success");
	const warning = tokenHex("warning");
	const error = tokenHex("error");
	const info = tokenHex("info");
	const dim = tokenHex("dim");
	const muted = tokenHex("muted");
	const frame = tokenHex("frame");
	const frameStrong = tokenHex("frameStrong");
	return `# Generated by Clio Coder from its theme tokens. Changes are replaced when the managed profile regenerates.

[mgr]
cwd = { fg = "${accent}" }
hovered = { reversed = true }
preview_hovered = { underline = true }
find_keyword = { fg = "${warning}", bold = true }
find_position = { fg = "${action}", italic = true }
marker_selected = { fg = "${success}", bg = "${success}" }
marker_copied = { fg = "${accent}", bg = "${accent}" }
marker_cut = { fg = "${error}", bg = "${error}" }
marker_marked = { fg = "${info}", bg = "${info}" }
count_copied = { fg = "${accent}", bg = "${frame}" }
count_cut = { fg = "${error}", bg = "${frame}" }
count_selected = { fg = "${success}", bg = "${frame}" }
border_style = { fg = "${frame}" }
syntect_theme = ""

[mode]
normal_main = { bg = "${accent}", bold = true }
normal_alt = { fg = "${accent}" }
select_main = { bg = "${action}", bold = true }
select_alt = { fg = "${action}" }
unset_main = { bg = "${error}", bold = true }
unset_alt = { fg = "${error}" }

[tabs]
active = { bg = "${accent}", bold = true }
inactive = { fg = "${accent}" }

[status]
perm_type = { fg = "${accent}" }
perm_read = { fg = "${warning}" }
perm_write = { fg = "${error}" }
perm_exec = { fg = "${success}" }
perm_sep = { fg = "${dim}" }
progress_label = { bold = true }
progress_normal = { fg = "${accent}" }
progress_error = { fg = "${error}" }

[which]
cols = 3
mask = { bg = "${frame}" }
cand = { fg = "${accent}" }
rest = { fg = "${muted}" }
desc = { fg = "${action}" }
separator_style = { fg = "${dim}" }

[confirm]
border = { fg = "${frameStrong}" }
title = { fg = "${accent}" }
btn_yes = { reversed = true }
btn_no = {}

[pick]
border = { fg = "${frameStrong}" }
active = { fg = "${action}", bold = true }

[input]
border = { fg = "${frameStrong}" }
title = { fg = "${accent}" }
selected = { reversed = true }

[cmp]
border = { fg = "${frameStrong}" }
active = { reversed = true }

[tasks]
border = { fg = "${frameStrong}" }
title = { fg = "${accent}" }
hovered = { fg = "${action}", underline = true }

[help]
on = { fg = "${accent}" }
run = { fg = "${action}" }
footer = { fg = "${muted}" }

[notify]
title_info = { fg = "${info}" }
title_warn = { fg = "${warning}" }
title_error = { fg = "${error}" }
`;
}

/**
 * The same palette as a herdr `[theme.custom]` block.
 *
 * herdr themes its chrome (sidebar, tab bar, borders, agent rows) from its own
 * config.toml and has no per-pane styling on the wire, so Clio cannot color
 * the panes it opens. What it can do is hand the operator the block that makes
 * herdr's chrome match Clio, to paste into herdr's config; Clio never writes
 * another program's configuration itself.
 */
export function renderHerdrThemeBlock(): string {
	return `# Clio Coder theme tokens for herdr. Paste into ~/.config/herdr/config.toml, then run \`herdr server reload-config\`.
[theme.custom]
accent = "${tokenHex("accent")}"
green = "${tokenHex("success")}"
blue = "${tokenHex("info")}"
red = "${tokenHex("error")}"
yellow = "${tokenHex("warning")}"
selection_bg = "${tokenHex("frame")}"
active_row_bg = "${tokenHex("frame")}"
`;
}
