// Build-time projection; the installed app reads only its bundled assets.
import { execFileSync } from "node:child_process";
import { createHash } from "node:crypto";
import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";

const file = (path) => new URL(path, import.meta.url);
const source = await readFile(file("../../../site/design-system.json"));
const design = JSON.parse(source);
const roles = {
	paper: "paper",
	surface: "paper-raised",
	"surface-sunken": "paper-sunk",
	overlay: "paper-raised",
	ink: "ink",
	"ink-strong": "ink",
	"ink-muted": "muted",
	"ink-subtle": "muted",
	line: "line",
	"line-strong": "line-control",
	accent: "accent",
	"accent-strong": "accent",
	"accent-soft": "accent-soft",
	"on-accent": "on-accent",
	focus: "accent",
	"focus-halo": "paper",
	"primary-fill": "accent",
	"on-primary": "on-accent",
	selection: "accent-soft",
	secondary: "secondary",
};
const theme = (name) =>
	Object.entries(roles)
		.map(([key, role]) => `\t--${key}: ${design.palette[design.themes[name][role]]};`)
		.join("\n");
const font = (family, weight, name, style = "normal") =>
	`@font-face { font-family: "${family}"; font-style: ${style}; font-weight: ${weight}; font-display: swap; src: url("/fonts/${name}.woff2") format("woff2"); }`;
const css = `/* Generated by scripts/sync-brand.mjs from the canonical site export. */
${font("IBM Plex Sans", "100 700", "plex-sans")}
${font("IBM Plex Mono", "400", "plex-400")}
${font("IBM Plex Mono", "500", "plex-500")}
${font("Newsreader", "500", "news-normal-500")}
${font("Newsreader", "480", "news-italic-480", "italic")}
:root {
${theme("light")}
	--motion-fast: ${design.motion.fast};
	--motion-base: ${design.motion.base};
	--ease-standard: ${design.motion.ease};
	--ease-emphasis: ${design.motion.ease};
}
:root[data-theme="dark"] {
${theme("dark")}
}
@media (prefers-color-scheme: dark) {
	:root:not([data-theme="light"]) {
${theme("dark")}
	}
}
`;
const target = file("../client/design/brand.css");
const formatted = execFileSync("pnpm", ["exec", "biome", "format", "--stdin-file-path", fileURLToPath(target)], {
	input: css,
	encoding: "utf8",
	cwd: fileURLToPath(file("../")),
});
if (process.argv.includes("--check")) {
	if ((await readFile(target, "utf8")) !== formatted)
		throw new Error("GUI brand tokens drifted. Run scripts/sync-brand.mjs.");
	const provenance = JSON.parse(await readFile(file("../client/public/brand/provenance.json"), "utf8"));
	if (provenance.projection.designSha256 !== createHash("sha256").update(source).digest("hex"))
		throw new Error("GUI brand snapshot is stale. Export the canonical brand again.");
	for (const [name, hash] of Object.entries(provenance.projection.sha256))
		if (
			createHash("sha256")
				.update(await readFile(file(`../client/public/${name}`)))
				.digest("hex") !== hash
		)
			throw new Error(`GUI mark projection drifted: ${name}`);
	for (const name of [
		"plex-sans.woff2",
		"plex-400.woff2",
		"plex-500.woff2",
		"news-normal-500.woff2",
		"news-italic-480.woff2",
		"IBM-Plex-Sans-OFL.txt",
		"IBM-Plex-Mono-OFL.txt",
		"Newsreader-OFL.txt",
	])
		if (
			!(await readFile(file(`../client/public/fonts/${name}`))).equals(
				await readFile(file(`../../../site/assets/fonts/${name}`)),
			)
		)
			throw new Error(`GUI canonical font or notice differs: ${name}`);
	const mark = provenance.assets.find((asset) => asset.name === "clio-mark");
	if (
		!mark ||
		mark.sha256 !==
			createHash("sha256")
				.update(await readFile(file("../../../site/assets/brand/clio-mark.png")))
				.digest("hex")
	)
		throw new Error("GUI canonical mark provenance differs.");
} else await writeFile(target, formatted);
