/**
 * Regenerate skills/registry.yaml: the local pinned manifest of marketplace
 * skill content hashes. Run with `npm run skills:pin` after editing any
 * skills/<name>/SKILL.md.
 */

import { createHash } from "node:crypto";
import { existsSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import yaml from "yaml";

const repoRoot = path.resolve(import.meta.dirname, "..");
const catalogDir = path.join(repoRoot, "skills");
const manifestPath = path.join(catalogDir, "registry.yaml");

function sha256(value: string): string {
	return createHash("sha256").update(value, "utf8").digest("hex");
}

interface PinEntry {
	name: string;
	version: string | null;
	sha256: string;
}

const entries: PinEntry[] = [];
for (const dirent of readdirSync(catalogDir, { withFileTypes: true }).sort((a, b) => a.name.localeCompare(b.name))) {
	if (!dirent.isDirectory()) continue;
	const skillPath = path.join(catalogDir, dirent.name, "SKILL.md");
	if (!existsSync(skillPath)) continue;
	const raw = readFileSync(skillPath, "utf8");
	let name = dirent.name;
	let version: string | null = null;
	const fmMatch = raw.match(/^---\r?\n([\s\S]*?)\r?\n---(?:\r?\n|$)/);
	if (fmMatch?.[1]) {
		try {
			const fm = yaml.parse(fmMatch[1]) as Record<string, unknown> | null;
			if (fm && typeof fm.name === "string" && fm.name.trim().length > 0) name = fm.name.trim();
			const fmVersion = fm?.version ?? (fm?.metadata as Record<string, unknown> | undefined)?.version;
			if (typeof fmVersion === "string" && fmVersion.trim().length > 0) version = fmVersion.trim();
		} catch {
			// keep directory-name fallback
		}
	}
	entries.push({ name, version, sha256: sha256(raw) });
}

const manifest = [
	"# Pinned marketplace skill content hashes. Generated by `npm run skills:pin`.",
	"# At activation, an installed skill carrying registry-id provenance is",
	"# compared against its pinned sha256; a mismatch surfaces a drift warning.",
	yaml.stringify({ skills: entries }),
].join("\n");

writeFileSync(manifestPath, manifest, "utf8");
process.stdout.write(`pinned ${entries.length} skills -> ${manifestPath}\n`);
