import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { parse, stringify } from "yaml";
import { readPluginManifest } from "../src/domains/plugins/discovery.js";

const root = path.resolve(import.meta.dirname, "..");
const destination = path.join(root, "library", "registry.yaml");
const packages: string[] = [];
function collect(directory: string): void {
	if (existsSync(path.join(directory, "plugin.json"))) {
		packages.push(directory);
		return;
	}
	for (const item of readdirSync(directory, { withFileTypes: true })) {
		if (item.isDirectory() && !item.name.startsWith(".")) collect(path.join(directory, item.name));
	}
}
collect(path.join(root, "skills"));
collect(path.join(root, "plugins"));
const names = new Set<string>();
const entries = packages
	.map((directory) => {
		const candidate = readPluginManifest(directory);
		if (!candidate.valid || !candidate.manifest)
			throw new Error(`${directory}: ${candidate.diagnostics.map((item) => item.message).join("; ")}`);
		const manifest = candidate.manifest;
		const skillFile = path.join(directory, "SKILL.md");
		const frontmatter = existsSync(skillFile)
			? /^---\r?\n([\s\S]*?)\r?\n---/.exec(readFileSync(skillFile, "utf8"))?.[1]
			: undefined;
		const metadata = frontmatter ? (parse(frontmatter) as Record<string, unknown>) : {};
		const triggers = Array.isArray(metadata.triggers)
			? metadata.triggers.filter((item): item is string => typeof item === "string")
			: [];

		if (names.has(manifest.name)) throw new Error(`duplicate library package identity: ${manifest.name}`);
		names.add(manifest.name);
		return {
			kind: manifest.clio.kind ?? "plugin",
			name: manifest.name,
			description: manifest.description ?? "",
			...(manifest.clio.kind === "skill"
				? { category: path.basename(path.dirname(directory)), audit: "pass", ...(triggers.length ? { triggers } : {}) }
				: {}),
			version: manifest.version,
			sourceUrl: path.relative(path.dirname(destination), directory).split(path.sep).join("/"),
			sha256: candidate.contentDigest,
			...(manifest.clio.requires ? { requires: manifest.clio.requires } : {}),
		};
	})
	.sort((a, b) => a.name.localeCompare(b.name));
const content = `# Generated by pnpm library:pin. SHA-256 covers every package file.\n${stringify({ entries })}`;
if (process.argv.includes("--check")) {
	if (!existsSync(destination) || readFileSync(destination, "utf8") !== content) {
		process.stderr.write("Library pins are stale; run pnpm library:pin.\n");
		process.exitCode = 1;
	} else process.stdout.write(`Verified ${entries.length} full-tree library package pins.\n`);
} else {
	mkdirSync(path.dirname(destination), { recursive: true });
	writeFileSync(destination, content);
	process.stdout.write(`Pinned ${entries.length} library packages.\n`);
}
