import { existsSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { stringify } from "yaml";
import { readPluginManifest } from "../src/domains/plugins/discovery.js";
import { pluginContentDigest } from "../src/domains/plugins/integrity.js";

const args = process.argv.slice(2);
const dirAt = args.indexOf("--dir");
const directory = path.resolve(
	dirAt >= 0 && args[dirAt + 1] ? (args[dirAt + 1] as string) : path.join(import.meta.dirname, "..", "plugins"),
);
const check = args.includes("--check");
const entries = readdirSync(directory, { withFileTypes: true })
	.filter((entry) => entry.isDirectory() && existsSync(path.join(directory, entry.name, "plugin.json")))
	.sort((left, right) => left.name.localeCompare(right.name))
	.map((entry) => {
		const root = path.join(directory, entry.name);
		const candidate = readPluginManifest(root);
		if (!candidate.valid || !candidate.manifest)
			throw new Error(`${entry.name}: ${candidate.diagnostics.map((diagnostic) => diagnostic.message).join("; ")}`);
		if (!candidate.manifest.version) throw new Error(`${entry.name}: curated plugin requires a version`);
		return {
			name: candidate.manifest.name,
			description: candidate.manifest.description ?? "",
			version: candidate.manifest.version,
			sourceUrl: `./${entry.name}`,
			sha256: pluginContentDigest(root),
		};
	});
if (entries.length === 0) throw new Error("plugin catalog has no packages");
const destination = path.join(directory, "registry.yaml");
const content = `# Generated by pnpm plugins:pin. Every package file is integrity-bound.\n${stringify({ plugins: entries })}`;
if (check) {
	if (!existsSync(destination) || readFileSync(destination, "utf8") !== content) {
		process.stderr.write("Plugin pins are stale; run pnpm plugins:pin.\n");
		process.exitCode = 1;
	} else process.stdout.write(`Verified ${entries.length} full-tree plugin pin(s).\n`);
} else {
	writeFileSync(destination, content);
	process.stdout.write(`Pinned ${entries.length} plugin package(s).\n`);
}
