/**
 * Regenerate skills/registry.yaml: the local pinned manifest of marketplace
 * skill content hashes (provenance-stripped, so installed copies stamped with
 * install-lifecycle frontmatter still compare equal to their audited source).
 * Run with `npm run skills:pin` after editing any skills/<name>/SKILL.md.
 *
 * Modes:
 *   default          rewrite the manifest from the catalog
 *   --check          verify the manifest matches the catalog; exit 1 on drift
 *   --dir <path>     operate on a different catalog directory (tests)
 *
 * Malformed frontmatter is a hard failure in both modes: a skill file whose
 * YAML cannot be parsed must never be silently pinned under its folder name.
 * The catalog publishing contract (skills/README.md) is enforced here too:
 * every catalog skill must carry the required provenance frontmatter with
 * `audit: pass` and ship an evals.md beside its SKILL.md.
 */

import { existsSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import yaml from "yaml";
import { normalizedSkillHash } from "../src/domains/resources/skills/content-hash.js";

/** Frontmatter every published catalog skill must carry (skills/README.md). */
const REQUIRED_CATALOG_KEYS = ["name", "description", "version", "license", "registry-id", "source-url"] as const;

const argv = process.argv.slice(2);
const checkMode = argv.includes("--check");
const dirFlagIndex = argv.indexOf("--dir");
const repoRoot = path.resolve(import.meta.dirname, "..");
const catalogDir =
	dirFlagIndex >= 0 && argv[dirFlagIndex + 1]
		? path.resolve(argv[dirFlagIndex + 1] as string)
		: path.join(repoRoot, "skills");
const manifestPath = path.join(catalogDir, "registry.yaml");

interface PinEntry {
	name: string;
	version: string | null;
	sha256: string;
}

function collectEntries(): { entries: PinEntry[]; errors: string[] } {
	const entries: PinEntry[] = [];
	const errors: string[] = [];
	for (const dirent of readdirSync(catalogDir, { withFileTypes: true }).sort((a, b) => a.name.localeCompare(b.name))) {
		if (!dirent.isDirectory()) continue;
		const skillPath = path.join(catalogDir, dirent.name, "SKILL.md");
		if (!existsSync(skillPath)) continue;
		const raw = readFileSync(skillPath, "utf8");
		const fmMatch = raw.match(/^---\r?\n([\s\S]*?)\r?\n---(?:\r?\n|$)/);
		if (!fmMatch?.[1]) {
			errors.push(`${skillPath}: missing YAML frontmatter`);
			continue;
		}
		let fm: Record<string, unknown> | null;
		try {
			const parsed = yaml.parse(fmMatch[1]) as unknown;
			if (parsed === null || typeof parsed !== "object" || Array.isArray(parsed)) {
				errors.push(`${skillPath}: frontmatter must be a YAML object`);
				continue;
			}
			fm = parsed as Record<string, unknown>;
		} catch (err) {
			errors.push(`${skillPath}: invalid YAML frontmatter: ${err instanceof Error ? err.message : String(err)}`);
			continue;
		}
		let name = dirent.name;
		let version: string | null = null;
		if (typeof fm.name === "string" && fm.name.trim().length > 0) name = fm.name.trim();
		const fmVersion = fm.version ?? (fm.metadata as Record<string, unknown> | undefined)?.version;
		if (typeof fmVersion === "string" && fmVersion.trim().length > 0) version = fmVersion.trim();
		for (const key of REQUIRED_CATALOG_KEYS) {
			const value = fm[key];
			if (typeof value !== "string" || value.trim().length === 0) {
				errors.push(`${skillPath}: missing required catalog frontmatter "${key}"`);
			}
		}
		if (fm.audit !== "pass") {
			errors.push(`${skillPath}: catalog skills must carry "audit: pass" (found ${JSON.stringify(fm.audit ?? null)})`);
		}
		if (!existsSync(path.join(catalogDir, dirent.name, "evals.md"))) {
			errors.push(`${skillPath}: catalog skills must ship an evals.md beside SKILL.md`);
		}
		entries.push({ name, version, sha256: normalizedSkillHash(raw) });
	}
	return { entries, errors };
}

function renderManifest(entries: ReadonlyArray<PinEntry>): string {
	return [
		"# Pinned marketplace skill content hashes (provenance-stripped sha256).",
		"# Generated by `npm run skills:pin`. At activation, an installed skill",
		"# carrying registry-id provenance is compared against its pinned hash;",
		"# a mismatch surfaces a drift warning.",
		yaml.stringify({ skills: entries }),
	].join("\n");
}

/** Human drift summary: which pins are missing, stale, or orphaned. */
function describeDrift(current: string, expected: ReadonlyArray<PinEntry>): string[] {
	const lines: string[] = [];
	let pinned: PinEntry[] = [];
	try {
		const parsed = yaml.parse(current) as { skills?: PinEntry[] } | null;
		pinned = Array.isArray(parsed?.skills) ? parsed.skills : [];
	} catch {
		return ["registry.yaml is not parseable YAML"];
	}
	const pinnedByName = new Map(pinned.map((entry) => [entry.name, entry]));
	const expectedByName = new Map(expected.map((entry) => [entry.name, entry]));
	for (const entry of expected) {
		const pin = pinnedByName.get(entry.name);
		if (!pin) lines.push(`${entry.name}: in catalog but not pinned`);
		else if (pin.sha256 !== entry.sha256 || pin.version !== entry.version) lines.push(`${entry.name}: pin is stale`);
	}
	for (const pin of pinned) {
		if (!expectedByName.has(pin.name)) lines.push(`${pin.name}: pinned but not in catalog`);
	}
	return lines;
}

const { entries, errors } = collectEntries();
if (errors.length > 0) {
	for (const error of errors) process.stderr.write(`pin-skills: ${error}\n`);
	process.stderr.write(
		`pin-skills: ${errors.length} catalog contract violation(s); nothing was ${checkMode ? "checked" : "pinned"}\n`,
	);
	process.exit(1);
}

const manifest = renderManifest(entries);

if (checkMode) {
	let current: string | null = null;
	try {
		current = readFileSync(manifestPath, "utf8");
	} catch {
		current = null;
	}
	if (current === manifest) {
		process.stdout.write(`registry pin check ok (${entries.length} skills)\n`);
		process.exit(0);
	}
	process.stderr.write(`pin-skills: ${manifestPath} does not match the catalog content hashes\n`);
	for (const line of describeDrift(current ?? "", entries)) process.stderr.write(`pin-skills:   ${line}\n`);
	process.stderr.write("pin-skills: run `npm run skills:pin` and commit the result\n");
	process.exit(1);
}

writeFileSync(manifestPath, manifest, "utf8");
process.stdout.write(`pinned ${entries.length} skills -> ${manifestPath}\n`);
