import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { runCommandVector } from "../../../core/safe-exec.js";
import { safeResourceWrite } from "../../../core/safe-resource-write.js";
import { resolveClioDirs } from "../../../core/xdg.js";
import type { MusicStation } from "./stations.js";
import { renderCliampTheme } from "./theme.js";

/**
 * Clio's own cliamp home.
 *
 * cliamp reads its config directory from `CLIAMP_CONFIG_DIR` before
 * `XDG_CONFIG_HOME` and `~/.config/cliamp`, and keeps its IPC socket there
 * too. Pointing both the pane and every control command at this directory
 * gives Clio a private player: the operator's own `~/.config/cliamp` files are
 * never read or written, and a cliamp they run themselves keeps its socket.
 * It lives under the state root because cliamp writes runtime files beside
 * the config (socket, log, history).
 */
export const CLIAMP_PLAYLIST = "clio";
const CLIAMP_THEME = "clio";

export function cliampHome(stateDir: string = resolveClioDirs().state): string {
	return join(stateDir, "cliamp");
}

/** The env both the pane and the control commands run under. */
export function cliampEnv(home: string = cliampHome()): Record<string, string> {
	return { CLIAMP_CONFIG_DIR: home };
}

function tomlString(value: string): string {
	return JSON.stringify(value);
}

function renderPlaylist(stations: ReadonlyArray<MusicStation>): string {
	return stations
		.map((station) => `[[track]]\npath = ${tomlString(station.url)}\ntitle = ${tomlString(station.title)}\n`)
		.join("\n");
}

/**
 * Write the profile the pane plays from. Every file is Clio's and is rewritten
 * each time, so a theme or station change lands on the next open, and an
 * in-player theme pick (which cliamp saves into config.toml) does not stick.
 */
export function writeCliampProfile(stations: ReadonlyArray<MusicStation>, home: string = cliampHome()): string {
	// Bars rather than a volume-linked meter, so a quiet stream still moves.
	safeResourceWrite(
		join(home, "config.toml"),
		`# Generated by Clio Coder for the /music pane.\ntheme = "${CLIAMP_THEME}"\nvisualizer = "Bars"\nvis_volume_linked = false\nrepeat = "all"\n`,
	);
	safeResourceWrite(join(home, "themes", `${CLIAMP_THEME}.toml`), renderCliampTheme());
	writeCliampPlaylist(stations, home);
	return home;
}

const DOCK_PLUGIN = "clio-dock";

/** The file the dock plugin appends a line to on each Alt+A, read by the music session. */
export function cliampTapPath(home: string = cliampHome()): string {
	return join(home, "dock-taps");
}

/**
 * Lua for the one key Clio binds inside the player: Alt+A reports a tap to
 * Clio, which hides the pane and takes the keyboard back. cliamp's plugin
 * sandbox allows this binding with the `keymap` permission and a write inside
 * its own config directory, nothing more. The path is a JSON string, which Lua
 * reads the same way for any path an operator's state directory can hold.
 */
function renderDockPlugin(tapPath: string): string {
	return `-- Generated by Clio Coder. Changes are replaced and need approval again.
local p = plugin.register({
    name = ${JSON.stringify(DOCK_PLUGIN)},
    type = "hook",
    permissions = {"keymap"},
})
p:bind("alt+a", "Hide the music pane and return to Clio", function()
    cliamp.fs.append(${JSON.stringify(tapPath)}, "tap\\n")
end)
`;
}

/**
 * Write the dock plugin. True when cliamp must be told to trust it: its
 * approval manifest does not hold the hash of what is on disk now. cliamp runs
 * a plugin only after its exact contents were approved, so a stale approval is
 * the same as none.
 */
export function writeCliampDockPlugin(home: string = cliampHome()): boolean {
	const dir = join(home, "plugins");
	const file = join(dir, `${DOCK_PLUGIN}.lua`);
	const content = renderDockPlugin(cliampTapPath(home));
	let current: string | null = null;
	try {
		current = readFileSync(file, "utf8");
	} catch {
		// First write: there is no plugin to compare with.
	}
	if (current !== content) safeResourceWrite(file, content);
	const hash = createHash("sha256").update(content, "utf8").digest("hex");
	try {
		const manifest = JSON.parse(readFileSync(join(dir, ".trust.json"), "utf8")) as { plugins?: Record<string, unknown> };
		return manifest.plugins?.[DOCK_PLUGIN] !== hash;
	} catch {
		// No manifest, or one cliamp cannot read either: approve again.
		return true;
	}
}

/** Approve the plugin Clio just wrote. Clio authored the contents, so the prompt is answered for it. */
export async function trustCliampDockPlugin(binary: string, home: string = cliampHome()): Promise<boolean> {
	return (await cliampControl(binary, ["plugins", "trust", DOCK_PLUGIN, "--yes"], home)).ok;
}

export function writeCliampPlaylist(stations: ReadonlyArray<MusicStation>, home: string = cliampHome()): void {
	safeResourceWrite(join(home, "playlists", `${CLIAMP_PLAYLIST}.toml`), renderPlaylist(stations));
}

/**
 * argv the pane runs: the Clio playlist, loaded. `autoPlay` starts it at once;
 * without it the player sits stopped on the first station until resumed, which
 * is how a pane prepared at boot stays silent.
 */
export function cliampPaneArgv(binary: string, autoPlay = true): ReadonlyArray<string> {
	return [binary, "--playlist", CLIAMP_PLAYLIST, ...(autoPlay ? ["--auto-play"] : [])];
}

export interface CliampControlResult {
	ok: boolean;
	stdout: string;
	/** cliamp's own words on failure, such as "cliamp is not running". */
	error: string;
}

/** One IPC command against the pane's player, never the operator's. */
export async function cliampControl(
	binary: string,
	args: ReadonlyArray<string>,
	home: string = cliampHome(),
): Promise<CliampControlResult> {
	const result = await runCommandVector(binary, args, {
		cwd: home,
		workspaceRoot: home,
		env: cliampEnv(home),
		timeoutMs: 5_000,
	});
	const ok = result.exitCode === 0 && !result.timedOut;
	return {
		ok,
		stdout: result.stdout,
		error: ok ? "" : (result.stderr || result.stdout).trim() || "cliamp did not answer",
	};
}

export interface CliampStatus {
	state: string;
	title: string | null;
}

export async function cliampStatus(binary: string, home: string = cliampHome()): Promise<CliampStatus | null> {
	const result = await cliampControl(binary, ["status", "--json"], home);
	if (!result.ok) return null;
	try {
		const parsed = JSON.parse(result.stdout) as { state?: unknown; track?: { title?: unknown } };
		return {
			state: typeof parsed.state === "string" ? parsed.state : "unknown",
			title: typeof parsed.track?.title === "string" ? parsed.track.title : null,
		};
	} catch {
		// A status line that is not JSON is a player Clio cannot read, which is the same as no answer.
		return null;
	}
}
