import { join } from "node:path";
import { runCommandVector } from "../../../core/safe-exec.js";
import { safeResourceWrite } from "../../../core/safe-resource-write.js";
import { resolveClioDirs } from "../../../core/xdg.js";
import type { MusicStation } from "./stations.js";
import { renderCliampTheme } from "./theme.js";

/**
 * Clio's own cliamp home.
 *
 * cliamp reads its config directory from `CLIAMP_CONFIG_DIR` before
 * `XDG_CONFIG_HOME` and `~/.config/cliamp`, and keeps its IPC socket there
 * too. Pointing both the pane and every control command at this directory
 * gives Clio a private player: the operator's own `~/.config/cliamp` files are
 * never read or written, and a cliamp they run themselves keeps its socket.
 * It lives under the state root because cliamp writes runtime files beside
 * the config (socket, log, history).
 */
export const CLIAMP_PLAYLIST = "clio";
const CLIAMP_THEME = "clio";

export function cliampHome(stateDir: string = resolveClioDirs().state): string {
	return join(stateDir, "cliamp");
}

/** The env both the pane and the control commands run under. */
export function cliampEnv(home: string = cliampHome()): Record<string, string> {
	return { CLIAMP_CONFIG_DIR: home };
}

function tomlString(value: string): string {
	return JSON.stringify(value);
}

function renderPlaylist(stations: ReadonlyArray<MusicStation>): string {
	return stations
		.map((station) => `[[track]]\npath = ${tomlString(station.url)}\ntitle = ${tomlString(station.title)}\n`)
		.join("\n");
}

/**
 * Write the profile the pane plays from. Every file is Clio's and is rewritten
 * each time, so a theme or station change lands on the next open, and an
 * in-player theme pick (which cliamp saves into config.toml) does not stick.
 */
export function writeCliampProfile(stations: ReadonlyArray<MusicStation>, home: string = cliampHome()): string {
	// Bars rather than a volume-linked meter, so a quiet stream still moves.
	safeResourceWrite(
		join(home, "config.toml"),
		`# Generated by Clio Coder for the /music pane.\ntheme = "${CLIAMP_THEME}"\nvisualizer = "Bars"\nvis_volume_linked = false\nrepeat = "all"\n`,
	);
	safeResourceWrite(join(home, "themes", `${CLIAMP_THEME}.toml`), renderCliampTheme());
	writeCliampPlaylist(stations, home);
	return home;
}

export function writeCliampPlaylist(stations: ReadonlyArray<MusicStation>, home: string = cliampHome()): void {
	safeResourceWrite(join(home, "playlists", `${CLIAMP_PLAYLIST}.toml`), renderPlaylist(stations));
}

/** argv the pane runs: the Clio playlist, playing at once. */
export function cliampPaneArgv(binary: string): ReadonlyArray<string> {
	return [binary, "--playlist", CLIAMP_PLAYLIST, "--auto-play"];
}

export interface CliampControlResult {
	ok: boolean;
	stdout: string;
	/** cliamp's own words on failure, such as "cliamp is not running". */
	error: string;
}

/** One IPC command against the pane's player, never the operator's. */
export async function cliampControl(
	binary: string,
	args: ReadonlyArray<string>,
	home: string = cliampHome(),
): Promise<CliampControlResult> {
	const result = await runCommandVector(binary, args, {
		cwd: home,
		workspaceRoot: home,
		env: cliampEnv(home),
		timeoutMs: 5_000,
	});
	const ok = result.exitCode === 0 && !result.timedOut;
	return {
		ok,
		stdout: result.stdout,
		error: ok ? "" : (result.stderr || result.stdout).trim() || "cliamp did not answer",
	};
}

export interface CliampStatus {
	state: string;
	title: string | null;
}

export async function cliampStatus(binary: string, home: string = cliampHome()): Promise<CliampStatus | null> {
	const result = await cliampControl(binary, ["status", "--json"], home);
	if (!result.ok) return null;
	try {
		const parsed = JSON.parse(result.stdout) as { state?: unknown; track?: { title?: unknown } };
		return {
			state: typeof parsed.state === "string" ? parsed.state : "unknown",
			title: typeof parsed.track?.title === "string" ? parsed.track.title : null,
		};
	} catch {
		// A status line that is not JSON is a player Clio cannot read, which is the same as no answer.
		return null;
	}
}
