import { terminalBackground } from "../../../core/terminal-background.js";
import { roleHex } from "../../../core/theme-roles.js";

/**
 * Clio's cliamp theme, the six keys a cliamp 1.63 custom theme requires.
 *
 * Colors come from Clio's semantic roles (`core/theme-roles.ts`) for the
 * detected terminal background, the way the Yazi theme does. cliamp ignores a
 * theme that misses any key, so all six are always written. The spectrum runs
 * through `green`, `yellow` and `red` from low to high, which here is Clio's
 * cyan, turquoise and action accent rather than a traffic light.
 */
export function renderCliampTheme(): string {
	const background = terminalBackground();
	const hex = (role: Parameters<typeof roleHex>[0]): string => roleHex(role, background);
	return `# Generated by Clio Coder from its theme tokens. Rewritten on every /music on.
accent = "${hex("selectedOption")}"
bright_fg = "${hex("body")}"
fg = "${hex("metadata")}"
green = "${hex("toolGlyph")}"
yellow = "${hex("transcriptKnowledgeAction")}"
red = "${hex("harnessAction")}"
`;
}
